apiVersion: apps/v1
kind: Deployment
metadata:
  name: minecraft-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minecraft-server
  template:
    metadata:
      labels:
        app: minecraft-server
    spec:
      imagePullSecrets:
        - name: registry-pull-secret
      containers:
      - image: harbor.apps.c6.numerique-interieur.com/mc-minecraft/minecraft-server:e0d08e55
        name: minecraft-server
        ports:
        - containerPort: 25565
          protocol: TCP
        env:
        - name: EULA
          value: "TRUE"
        - name: MEMORY
          value: "1G"
        - name: TYPE
          value: "VANILLA"
        - name: VERSION
          value: "LATEST"
        - name: DIFFICULTY
          value: "easy"
        - name: MAX_PLAYERS
          value: "10"
        - name: OPS
          value: "your_minecraft_username"
        resources:
          limits:
            cpu: 2
            memory: 2Gi
          requests:
            cpu: 1
            memory: 1Gi
